# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 13:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='imageLocation',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='avgcustomerRating',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='context',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.BigIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='book',
            name='displayTitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='image_back',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='book',
            name='image_front',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.BigIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn10',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn13',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='maxretailprice',
            field=models.BigIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='book',
            name='minimumprice',
            field=models.BigIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='book',
            name='newArrival',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='book',
            name='publishingDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='pustakalayRating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='book',
            name='rank',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='sku',
            field=models.CharField(blank=True, default=b'pu', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='book',
            name='subCategory',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='book',
            name='format',
            field=models.CharField(choices=[(b'PAPERBACK', b'Paperback'), (b'HARDCOVER', b'Hardcover'), (b'EBOOK', b'Ebook')], default=b'Paperback', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[(b'HINDI', b'Hindi'), (b'ENGLISH', b'English'), (b'MARATHI', b'Marathi')], default=b'English', max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='numberOfPages',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.BigIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='translatedBy',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
