# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_auto_20180707_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='aboutAuthor',
            field=models.CharField(default='N', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishingDate',
            field=models.DateField(blank=True),
        ),
    ]
