# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_auto_20180707_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='aboutAuthor',
            field=models.TextField(max_length=20000),
        ),
    ]
